version: 2
updates:
  # Enable version updates for Elixir/Mix dependencies
  - package-ecosystem: "mix"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "security-team"
    assignees:
      - "maintainer"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    labels:
      - "dependencies"
      - "elixir"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
        update-types: ["version-update:semver-patch", "version-update:semver-minor"]
    ignore:
      # Ignore major version updates for critical dependencies
      - dependency-name: "phoenix"
        update-types: ["version-update:semver-major"]
      - dependency-name: "ecto_sql"
        update-types: ["version-update:semver-major"]

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 3
    reviewers:
      - "devops-team"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "github-actions"
      - "ci"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
    open-pull-requests-limit: 2
    reviewers:
      - "devops-team"
    commit-message:
      prefix: "docker"
      include: "scope"
    labels:
      - "docker"
      - "infrastructure"

  # Enable version updates for NPM (if assets use Node.js)
  - package-ecosystem: "npm"
    directory: "/assets"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "frontend-team"
    commit-message:
      prefix: "assets"
      include: "scope"
    labels:
      - "dependencies"
      - "assets"
      - "javascript"
    versioning-strategy: increase