apiVersion: v1
kind: Service
metadata:
  name: slack-clone
  namespace: slack-clone-staging
  labels:
    app: slack-clone
    environment: staging
spec:
  type: ClusterIP
  ports:
  - port: 4000
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: slack-clone
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: slack-clone-ingress
  namespace: slack-clone-staging
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/rate-limit: "100"
    nginx.ingress.kubernetes.io/rate-limit-window: "1m"
spec:
  tls:
  - hosts:
    - slack-clone-staging.yourdomain.com
    secretName: slack-clone-staging-tls
  rules:
  - host: slack-clone-staging.yourdomain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: slack-clone
            port:
              number: 4000